extends Node3D
class_name CharacterVisual

## Owns everything about how a unit LOOKS, so `character_base.gd` never has to
## know the shape of the mesh tree. Sits on `CharacterBase.tscn`'s `Visual`
## node, which `camera_rig.gd` already treats as one hideable subtree for the
## FPP self-hide.
##
## Why this exists as its own script rather than a mesh wired into
## CharacterBase.tscn: `is_can` FLIPS EVERY ROUND (roles swap — see
## main.gd::_reset_world), so a Prop is a Can one round and a Tsinelas the next.
## The model has to be swappable at runtime, not baked into the scene.
##
## It also owns the B-44 hit flash. That used to be
## `get_node_or_null("Visual/MeshInstance3D")` in character_base.gd, and it has
## already broken silently once (commit 6f97e76) when the mesh moved under the
## `Visual` wrapper — a hardcoded node path returns null with no error and the
## flash just stops happening. Nothing here depends on a fixed path: the meshes
## are whatever `find_children` turns up under the model that was actually
## instanced, so restructuring a visual scene cannot break it.

## Persons are Kenney "Mini Characters" (CC0 — see KENNEY_LICENSE.txt). Indexed
## by team, so index 0 and 1 are the two Persons you actually see in a match and
## the rest are the character-select roster (B-24).
##
## Order is deliberate, not alphabetical:
##   [0] male-f   — the reference character from the art direction: dark blocky
##                  hair, heavy brow, green top over a tan body.
##   [1] female-f — Team B's default, picked to contrast [0] on the two things
##                  readable at gameplay distance: ginger hair against dark, and
##                  a black/yellow outfit against green.
## Everything after those two is roster stock. Do not reorder the first two
## without checking both still read apart from across the arena.
const PERSON_MODELS: Array[String] = [
	"res://assets/characters/persons/character-male-f.glb",
	"res://assets/characters/persons/character-female-f.glb",
	"res://assets/characters/persons/character-male-a.glb",
	"res://assets/characters/persons/character-female-a.glb",
	"res://assets/characters/persons/character-male-b.glb",
	"res://assets/characters/persons/character-female-b.glb",
	"res://assets/characters/persons/character-male-c.glb",
	"res://assets/characters/persons/character-female-c.glb",
	"res://assets/characters/persons/character-male-d.glb",
	"res://assets/characters/persons/character-female-d.glb",
	"res://assets/characters/persons/character-male-e.glb",
	"res://assets/characters/persons/character-female-e.glb",
]
const CAN_VISUAL: String = "res://scenes/characters/visuals/CanVisual.tscn"
const TSINELAS_VISUAL: String = "res://scenes/characters/visuals/TsinelasVisual.tscn"

## M-2: the lata's damage states, indexed BY DENT COUNT — index 0 is pristine, so
## `CAN_MESHES[dents]` is the whole lookup. Generated by
## tools/models/generate_all.gd; regenerate rather than editing the .obj.
##
## Under Option A the dent count IS the Can's health, and this is the only place
## a player can read it in the world rather than off the HUD. `character_base.gd`
## must never learn that dents have a mesh — it owns the number, this file owns
## what the number looks like.
## ⚠️ CHECKLIST 7.2 — these are Kenney Food Kit `.glb` files now, not the four
## generated `lata*.obj` meshes. The kit ships TWO states against the four this
## system uses, so the middle two are the intact can progressively squashed
## (`CAN_DENT_SQUASH` below) rather than four distinct meshes. Authoring real
## intermediate crush meshes is later polish, not a blocker — the read that
## matters is "it looks worse each time you hit it", and a squash delivers that.
##
## The interface is unchanged: `CAN_MESHES[dents]` is still the whole lookup and
## `character_base.gd` still owns the number without knowing dents have a mesh.
const CAN_MESHES: Array[String] = [
	"res://assets/models/kits/food/soda-can.glb",
	"res://assets/models/kits/food/soda-can.glb",
	"res://assets/models/kits/food/soda-can.glb",
	"res://assets/models/kits/food/soda-can-crushed.glb",
]
## Vertical squash per dent count, applied to the mesh instance. Index 3 is 1.0
## because `soda-can-crushed` is already a crushed mesh — squashing it too would
## read as a puddle rather than a can.
const CAN_DENT_SQUASH: Array[float] = [1.0, 0.93, 0.85, 1.0]

## Knocked-down is a ROTATION, not a mesh (Handoff.md §4, M-2 step 5) — the can
## falls on its side and gets back up, and baking that into geometry would mean
## eight meshes instead of four.
const DOWNED_TILT_DEGREES: float = 78.0
const DOWNED_TILT_TIME: float = 0.28

## Locomotion thresholds in units/second. CharacterBase.SPEED is 6.0 and a dash
## burst is 14.0, so `sprint` is reserved for the dash and normal movement walks.
const WALK_SPEED_THRESHOLD: float = 0.4
const RUN_SPEED_THRESHOLD: float = 7.5

## One-shot clips per action, in preference order — the first one the model
## actually has wins. Kenney's roster ships all 32 for the Persons; a Prop has no
## AnimationPlayer at all and `play_action` no-ops there.
const ACTION_CLIPS: Dictionary = {
	# The Person's Tag/Throw. `pick-up` is the grab read the brief asked for;
	# the holding-*-shoot pair are the throw follow-through.
	"throw": ["holding-right-shoot", "pick-up", "interact-right"] as Array[String],
	# Bump — a shove, so a melee swing rather than a throw.
	"bump": ["attack-melee-right", "attack-kick-right", "interact-right"] as Array[String],
	# 7.7 — the ready-up press, so everyone ELSE can see who has readied without
	# looking at a HUD. `emote-yes` is literally a thumbs-up on this rig; it was
	# one of the 24 clips shipping unused.
	"ready": ["emote-yes", "interact-right"] as Array[String],
	# Task 1 — reaching down for a loose tsinelas. `pick-up` is the literal clip
	# for this and the reason the brief called it out.
	"grab": ["pick-up", "interact-right", "interact-left"] as Array[String],
}

## The Kenney rig is authored ~0.67 units tall with its origin at the feet, so
## this brings it up to the ~1.6 units of CharacterBase's CapsuleShape3D.
## Measured from the imported model's AABB, not guessed.
const PERSON_SCALE: float = 2.38
## FALLBACK ONLY — used when `_character` or its `CollisionShape3D` can't be
## read (e.g. a preview scene with no CharacterBase parent). Every real unit in
## a match reads its OWN capsule height instead; see `_align_to_capsule_floor`.
## ⚠️ Was the ONLY value, unconditionally, before Art_Direction.md §1 gave
## Can/Tsinelas their own much shorter capsules — B-88: with this left hardcoded,
## `_align_to_capsule_floor` kept dropping every model a full 0.8 units below its
## OWN origin regardless of its actual (now much smaller) capsule, which for a
## can (half-height 0.17) put the visible mesh 0.63 units under the floor. The
## can and tsinelas render fine on their own preview turntable and disappear
## the moment they're an actual in-game unit — that split is the signature of
## reading the wrong capsule rather than a bad mesh.
const CAPSULE_HALF_HEIGHT_DOWN: float = -0.8

## Task 0 / Task 1 — where a carried tsinelas rides. The Kenney rig has SEVEN
## bones (root, leg-left, leg-right, torso, arm-left, arm-right, head) and the
## arms are not separate meshes; they are skinned inside `body-mesh`. So a held
## item cannot be parented to "the arm mesh" — there isn't one. It has to hang
## off a BoneAttachment3D on the arm BONE, which is what _build_hand_attachment
## below does.
##
## Right hand first: `holding-right`, `holding-right-shoot` and
## `attack-melee-right` are the clips that actually exist on this rig, so the
## right arm is the one the animation set is built around. `arm-left` is only a
## fallback for a model that somehow lacks the right one.
const HAND_BONE_CANDIDATES: Array[String] = ["arm-right", "arm-left"]
## Offset from the arm bone to the point a carried unit's ORIGIN should sit —
## note: its origin, not its palm. A CharacterBase's origin is the centre of its
## 1.6-unit capsule, while its visible model is dropped to the capsule floor by
## _align_to_capsule_floor, so parking the origin exactly at the palm would hang
## the slipper most of a metre below the hand. This offset absorbs that, and it
## lives HERE rather than in carriable.gd on purpose: it is a fact about how the
## model is laid out, and character_base.gd must never learn it — same rule that
## keeps dents out of it.
##
## ⚠️ WORLD UNITS, in the arm bone's rotated frame — NOT bone-local units.
## `_build_hand_attachment` divides by PERSON_SCALE before writing it, because
## the HandPoint hangs off a BoneAttachment3D whose global basis already carries
## the model's 2.38 scale. The original code wrote this constant straight onto
## the node, so every component was silently multiplied by 2.38: the measured
## result was a slipper parked at CharacterBase-local (-1.00, +1.12, -0.45) —
## a metre out to the character's left and above the top of its own head, which
## is where "the held slipper isn't in their hand" came from. Verified in-engine
## by rendering it, not by reading it.
## ⚠️ RE-MEASURED for Art_Direction.md §1 — the tsinelas mesh is now natively
## 0.32x scale (generate_all.gd's TSINELAS_SCALE) instead of being shrunk at
## runtime by the since-deleted TSINELAS_CARRY_SCALE. That runtime scale used to
## apply to the `Visual` node itself, about ITS OWN ORIGIN — so while carried,
## the slipper's sole (dropped to local y = -0.8 by _align_to_capsule_floor) was
## effectively lifted to -0.8 * 0.32 = -0.256. With no runtime scaling left,
## Visual.scale is always Vector3.ONE, so the sole sits at the FULL -0.8 in
## every carry state unless the target absorbs it.
##
## Re-measured by rendering, not by keeping the old apparent position: the first
## attempt held the mesh's apparent height constant (target.y 0.470 -> 1.014,
## same -0.8 drop applied), which put the slipper at the same HEIGHT as before —
## but forward distance (Z) was unchanged, and unlike the old dynamically-shrunk
## mesh, this one is elongated along its own local axis and the arm bone's fixed
## rotation turns that axis nearly broadside to the FPP camera. Broadside and
## close together is worse than either alone: `tools/render_probe.gd`'s
## viewmodel mode showed it filling most of the frame. Pushing it further out
## (larger |Z|) and back down closer to the old un-compensated height (Y well
## below the +0.45 eye, rather than above it) reads correctly in both the FPP
## screenshot and the third-person one — small, forward, off to the side of
## the crosshair, and visibly attached to the hand rather than floating loose.
## ⚠️ MEASURED BY CALIBRATION, NOT GUESSED — and it is only valid for the
## `holding-right` pose. Change that pose and this is wrong again; re-measure
## rather than nudging it by eye.
##
## The offset is applied in the ARM BONE's rotated frame, so it is not readable
## by inspection. Calibrated by sampling the HandPoint that render_probe reports
## at four offsets — (0,0,0) and the three unit axes — which gives the map
## exactly:
##
##     world = t + R * offset
##     t = (-0.2378, -0.1152, -0.0411)   (the arm bone's origin, character-local)
##     R = a +60 degree rotation about Y:  x -> (0.5, 0, -0.866)
##                                         z -> (0.866, 0, 0.5)
##
## Inverting that puts the slipper wherever you want it in CHARACTER space:
##     offset = R⁻¹ * (target - t),  R⁻¹: x -> 0.5x - 0.866z,  z -> 0.866x + 0.5z
##
## THE TARGET WAS CHOSEN FOR FIRST PERSON, because a Person is always FPP and
## the carried slipper is the thing they aim with. Its origin lands at
## (0.260, 0.600, -0.750): the ORIGIN sits a little above the eye (+0.45), but
## the visible mesh drops 0.8 below that once instanced, landing it comfortably
## below the eyeline. Forward and to the right so it never covers the
## crosshair, and far enough out that the mesh's long axis (turned nearly
## broadside to the camera by the arm bone's own fixed rotation) doesn't fill
## the frame the way a closer placement did.
##
## Three earlier attempts are worth recording so nobody repeats them. Targeting
## "chest height" put it beside the head — this rig is chibi and its head spans
## +0.017 to +0.798, so ordinary human landmarks do not transfer. Targeting the
## palm itself buried it inside the arm mesh and dropped it ~60 degrees below the
## camera, i.e. outside a 75-degree FOV entirely: correct in the hand, invisible
## to the player. Targeting the SAME apparent height the old dynamically-shrunk
## mesh read at (character-local Y 0.214, i.e. target.y 1.014) put the object
## close to the eye's own height, which put it close to the CAMERA in total 3D
## distance too — broadside and close together filled most of the frame.
const HAND_CARRY_OFFSET: Vector3 = Vector3(0.863, 0.715, 0.077)

## The persistent carry pose. Verified against the actual .glb rather than a
## doc: the Kenney rig ships `holding-right` and `holding-right-shoot`, and
## `HAND_BONE_CANDIDATES` already prefers the right arm for exactly that reason.
## There is NO `holding-right-walk` on this rig, so a carrying Person who starts
## moving falls back to plain `walk` — the slipper still tracks the arm bone
## through the BoneAttachment3D, so it stays in hand either way.
const CARRY_IDLE_CLIP: String = "holding-right"

const FLASH_DURATION: float = 0.15

## 4.2 — remote movement interpolation. A non-authority networked character's
## `position`/`rotation` (CharacterBase.tscn's MultiplayerSynchronizer) are
## written straight onto the BODY every time a replicated update lands, and
## must stay that way — collision, the Hitbox offset and every directional
## ability read the body transform directly (Agent_Prompts.md's Netcode
## brief §3). This node exists as the wrapper for exactly this kind of
## decoupling: it lags a WORLD-space copy of the body's position/yaw behind
## by this rate and renders the mesh from that instead, so the body can keep
## snapping for gameplay while what you actually SEE glides. Higher = closes
## the gap faster (less visible lag, less jitter hidden); tuned to disappear
## within a couple of physics ticks on a LAN rather than read as "floaty".
const REMOTE_SMOOTH_RATE: float = 18.0

## M-4: toon+outline shaders for Prop (Can/Tsinelas) models. Persons are
## excluded (M-4 step 4) — their glTF ORMMaterial3D interacts badly with
## ShaderMaterial in _collect_meshes and the interaction is fixed in M-5.
## Loaded once and shared across all instances; the per-instance albedo_color
## uniform lives in the duplicated ShaderMaterial, not in the shared Shader.
const TOON_SHADER: Shader = preload("res://assets/models/materials/toon.gdshader")
const OUTLINE_SHADER: Shader = preload("res://assets/models/materials/outline.gdshader")

## Q-8: impact particle burst on a landed hit — the moodboard's "IMPACT EFFECT
## (particle burst)". Built from a primitive + StandardMaterial3D in code, no
## art asset. Roughly chest height so it reads against the character instead
## of bursting at ground level.
const IMPACT_PARTICLE_COUNT: int = 16
const IMPACT_PARTICLE_LIFETIME: float = 0.4
const IMPACT_PARTICLE_HEIGHT: float = 1.0

## Emitted whenever the instanced model is replaced. `camera_rig.gd` listens so
## it can re-apply the FPP self-hide: rig `_ready()` runs BEFORE
## `character_base.gd`'s (children are ready before parents), so at the moment
## the rig first looks for meshes to hide, this node is still empty — and every
## round-swap replaces them again. Without this, a Person's own body renders
## solid in first person and you look at the inside of your own head.
signal model_changed

## Which model is currently instanced, so a `refresh()` that doesn't actually
## change anything (the idempotent double call from `_reset_world` →
## `reset_for_new_round`) doesn't rebuild the mesh tree and restart animation.
var _current_key: String = ""
## The per-surface materials this unit owns, not the MeshInstance3Ds — a model
## can have several surfaces per mesh, and keying the flash off surface 0 would
## silently miss the rest and desync from the albedo list.
var _materials: Array[BaseMaterial3D] = []
## Parallel to `_materials`: the albedo each one started at, so a flash always
## tweens back to the real colour rather than to whatever it was mid-flash.
var _base_albedos: Array[Color] = []
## M-4: toon-shader surfaces on Prop models. flash_hit() / flash_blocked() drive
## their uniforms directly, since ShaderMaterial has no albedo_color property.
## ⚠️ 7.1: tracked by their `flash_amount` uniform, and no base colour is stored
## alongside them any more — the flash is its own uniform now and tweens 1 -> 0,
## so there is nothing to restore. The outline next_pass materials carry no
## `flash_amount` and are deliberately NOT tracked; they must never flash.
var _shader_materials: Array[ShaderMaterial] = []
var _flash_tween: Tween = null
## The unit this Visual belongs to. Read for `dents` when a model is rebuilt
## mid-round — a Prop that swaps Can/Tsinelas/Can has to come back wearing the
## damage it already had, not a fresh pristine can.
var _character: CharacterBase = null
var _tilt_tween: Tween = null
## The instanced model's AnimationPlayer, or null for a Can/Tsinelas.
var _animator: AnimationPlayer = null
## Name of the one-shot action clip currently playing; empty when locomotion owns
## the animator. Guards _play_locomotion from stomping a throw mid-swing.
var _action_clip: String = ""
## Cached BoneAttachment3D child marking the hand. Rebuilt lazily rather than in
## apply(), because apply() also runs for Cans and Tsinelas that will never carry
## anything and a BoneAttachment3D on a model with no Skeleton3D is just waste.
## Invalidated (not freed — it dies with the model tree) on every model swap.
var _hand_attachment: Node3D = null

## 4.2 — this node's own lagged WORLD-space copy of the body's position/yaw.
## Only ever advanced for a non-authority networked character with nothing
## driving its movement (see _should_smooth_remote) — everyone else leaves
## this untouched and pays nothing for it. `false` until the first frame that
## actually needs smoothing, so a brand-new unit's first appearance snaps
## rather than gliding in from the world origin.
var _smoothed_world_pos: Vector3 = Vector3.ZERO
var _smoothed_yaw: float = 0.0
var _smoothing_initialized: bool = false

func _ready() -> void:
	# Children are ready before parents, so CharacterBase's own _ready() has not
	# run yet — connecting to its signals here is still safe (they are
	# declarations, not state) and guarantees we never miss the first dent.
	_character = get_parent() as CharacterBase
	if _character == null:
		return
	_character.dents_changed.connect(_on_dents_changed)
	_character.state_changed.connect(_on_state_changed)

## Option A: swap in the lata carrying this many dents. Nothing else in the
## codebase needs to know these meshes exist.
func _on_dents_changed(new_dents: int) -> void:
	_refresh_can_damage(new_dents)

func _on_state_changed(new_state: CharacterBase.State) -> void:
	_refresh_downed_tilt(new_state == CharacterBase.State.DOWNED)

## 7.2 — a Mesh from either a bare mesh resource or an imported model SCENE.
##
## ⚠️ THE KIT SWAP MADE THIS NECESSARY. `load(path) as Mesh` worked while the
## can was a `.obj`, which Godot imports as a Mesh. A `.glb` imports as a
## PackedScene, so the same cast silently yields `null` and the can simply
## stops changing on damage — no error, no missing mesh, just a dent count that
## never shows. Handles both so a future asset can be either.
##
## The instance is freed immediately: only its Mesh resource is kept, and
## leaving the node alive would leak one throwaway scene per dent taken.
func _mesh_from(path: String) -> Mesh:
	var resource := load(path)
	if resource is Mesh:
		return resource as Mesh
	var packed := resource as PackedScene
	if packed == null:
		return null
	var instance := packed.instantiate() as Node3D
	if instance == null:
		return null
	var found: Mesh = null
	for node in instance.find_children("*", "MeshInstance3D", true, false):
		found = (node as MeshInstance3D).mesh
		if found != null:
			break
	instance.free()
	return found

## Replaces the can's mesh in place rather than rebuilding the model tree — a
## rebuild would restart animation and re-run the whole instantiate path for what
## is a one-resource change.
func _refresh_can_damage(dent_count: int) -> void:
	if _current_key != CAN_VISUAL:
		return # a Tsinelas or a Person has no dents to show
	var model := get_child(0) as Node3D if get_child_count() > 0 else null
	if model == null:
		return
	var meshes := model.find_children("*", "MeshInstance3D", true, false)
	if meshes.is_empty():
		return
	var index := clampi(dent_count, 0, CAN_MESHES.size() - 1)
	var mesh_path: String = CAN_MESHES[index]
	var mesh := _mesh_from(mesh_path)
	if mesh == null:
		push_error("CharacterVisual: could not load a mesh from '%s'" % mesh_path)
		return
	var target := meshes[0] as MeshInstance3D
	target.mesh = mesh
	# 7.2 — the dent read for the two states the kit does not ship. Scale, not a
	# mesh, so it costs nothing and cannot drift out of sync with CAN_MESHES.
	var squash: float = CAN_DENT_SQUASH[index]
	target.scale = Vector3(1.0, squash, 1.0)
	# The swapped-in mesh arrives with the IMPORTER's shared materials, not this
	# unit's duplicated ones, so re-collect or the B-44 hit flash silently starts
	# tinting every can in the match at once. The toon ShaderMaterial overrides set
	# by _apply_toon_pass() survive a mesh swap (Godot does not clear overrides on
	# mesh assignment), so _collect_meshes() re-duplicates them correctly.
	_materials.clear()
	_base_albedos.clear()
	_shader_materials.clear()
	_collect_meshes(model)
	_align_to_capsule_floor(model)
	# camera_rig.gd re-applies the FPP self-hide on this signal; a new mesh that
	# never announced itself would render solid in first person (B-61).
	model_changed.emit()

## Tips the can onto its side while Downed and stands it back up on recovery.
## Only ever a Can — a toppled Person or Tsinelas would read as a bug.
func _refresh_downed_tilt(is_downed: bool) -> void:
	if _character == null or not _character.is_can:
		rotation.z = 0.0
		return
	if _tilt_tween != null and _tilt_tween.is_valid():
		_tilt_tween.kill()
	_tilt_tween = create_tween().set_trans(Tween.TRANS_BACK).set_ease(Tween.EASE_OUT)
	_tilt_tween.tween_property(self, "rotation:z",
		deg_to_rad(DOWNED_TILT_DEGREES) if is_downed else 0.0, DOWNED_TILT_TIME)

## Builds (or rebuilds) the model for this unit. Safe to call every round.
func apply(is_person: bool, is_can: bool, team: int) -> void:
	var key := _model_path(is_person, is_can, team)
	if key == _current_key:
		return
	_current_key = key

	if _flash_tween != null and _flash_tween.is_valid():
		_flash_tween.kill()
	for child in get_children():
		# remove_child BEFORE queue_free, not queue_free alone. queue_free only
		# schedules deletion for end of frame, so the outgoing model stays in the
		# tree and keeps being drawn while its duplicated materials are already
		# being released — which the renderer reports as "Parameter 'material' is
		# null" once per server call, on the one frame a model is swapped.
		remove_child(child)
		child.queue_free()
	_materials.clear()
	_base_albedos.clear()
	_shader_materials.clear()
	# The old AnimationPlayer went with the old model tree; holding a freed
	# reference here would make the first play_action() after a role swap throw.
	_animator = null
	_action_clip = ""
	# Same reasoning: the BoneAttachment3D was a child of the outgoing skeleton
	# and has just been freed with it. Null it rather than rebuilding eagerly —
	# get_hand_attachment() rebuilds on demand, and most units never carry.
	_hand_attachment = null

	var scene := load(key) as PackedScene
	if scene == null:
		push_error("CharacterVisual: could not load model '%s'" % key)
		return
	var model := scene.instantiate() as Node3D
	if is_person:
		model.scale = Vector3.ONE * PERSON_SCALE
	add_child(model)

	_apply_toon_pass(model, is_person)
	_collect_meshes(model)
	_align_to_capsule_floor(model)
	_play_idle(model)
	model_changed.emit()
	# A rebuild produces a pristine model, so re-apply whatever damage and
	# posture this unit already carries. Without this, a Prop that swapped
	# Tsinelas -> Can mid-match would come back with a clean lata and stand
	# upright while still Downed.
	if _character != null:
		_refresh_can_damage(_character.dents)
		_refresh_downed_tilt(_character.state == CharacterBase.State.DOWNED)

## Task 1 — the node a carried tsinelas snaps to. Returns null for anything with
## no skeleton (a Can, a Tsinelas, or a Person whose model has not been instanced
## yet), which callers must treat as "not ready", never as an error: this file's
## own `apply()` runs from character_base.gd's `_ready()`, so there is a real
## window early in a match where a Person exists and its hand does not.
##
## The returned node's transform is where the carried unit's ORIGIN goes — see
## HAND_CARRY_OFFSET. Its scale is deliberately meaningless: a Person model is
## scaled PERSON_SCALE (2.38) and every bone under it inherits that, so a caller
## copying this transform wholesale would inflate the slipper to match. Callers
## orthonormalise; carriable.gd::_step_carried documents why at the call site.
func get_hand_attachment() -> Node3D:
	if _hand_attachment != null and is_instance_valid(_hand_attachment):
		return _hand_attachment
	_hand_attachment = _build_hand_attachment()
	return _hand_attachment

func _build_hand_attachment() -> Node3D:
	if get_child_count() == 0:
		return null
	var model := get_child(0) as Node3D
	if model == null:
		return null
	var skeletons := model.find_children("*", "Skeleton3D", true, false)
	if skeletons.is_empty():
		return null
	var skeleton := skeletons[0] as Skeleton3D
	for bone_name in HAND_BONE_CANDIDATES:
		if skeleton.find_bone(bone_name) == -1:
			continue
		var attachment := BoneAttachment3D.new()
		attachment.name = "HandAttachment"
		attachment.bone_name = bone_name
		skeleton.add_child(attachment)
		# A separate child, rather than offsetting the BoneAttachment3D itself:
		# BoneAttachment3D overwrites its own transform from the bone pose every
		# frame, so anything written directly onto it is silently discarded on
		# the next update. This has bitten people in far less obvious ways than
		# it will here — the item simply sits at the elbow and nothing errors.
		var point := Node3D.new()
		point.name = "HandPoint"
		# Divided by PERSON_SCALE: this node's parent chain runs through the
		# Skeleton3D, which inherits the model's 2.38 scale, so a raw assignment
		# lands at 2.38x. See HAND_CARRY_OFFSET's own note.
		point.position = HAND_CARRY_OFFSET / PERSON_SCALE
		attachment.add_child(point)
		return point
	return null

## Drops the model so its lowest point rests on the bottom of CharacterBase's
## capsule, measured from the model that was actually instanced rather than
## carried as a per-model magic number. The Can (1.13 units) and the Tsinelas
## (1.35) are both shorter than the 1.6 capsule and would otherwise hover a
## visible 13-24cm above the ground, and the two Kenney Persons aren't even the
## same height as each other (1.60 vs 1.85 — hair), so one shared offset cannot
## be right for all four.
func _align_to_capsule_floor(model: Node3D) -> void:
	var bounds := AABB()
	var first := true
	for node in model.find_children("*", "VisualInstance3D", true, false):
		var box: AABB = (node as VisualInstance3D).get_aabb()
		box = (node as Node3D).transform * box
		if first:
			bounds = box
			first = false
		else:
			bounds = bounds.merge(box)
	if first:
		return # nothing to measure
	# ASSIGNMENT, not `+=`. The bounds are measured in the model's own local
	# space and do not include `model.position`, so `+=` re-applied the whole
	# offset every call and sank the model further each time. Harmless while this
	# only ever ran once per instantiate; M-2's dent swap calls it again on the
	# same model, which is what exposed it.
	model.position.y = _capsule_half_height_down() - bounds.position.y * model.scale.y

## B-88 — reads THIS unit's own, currently-applied capsule height (via
## CharacterBase.capsule_height(), the shared accessor every per-role-size
## reader now uses) rather than assuming the single shared 1.6 every unit used
## to have. Per-unit collision (Art_Direction.md §1,
## character_base.gd::_apply_role_collision()) means a Can and a Tsinelas now
## carry a much shorter capsule than a Person, and the capsule floor a model
## drops to has to track whichever one THIS character actually has — not a
## constant tuned for the Person alone.
func _capsule_half_height_down() -> float:
	if _character != null:
		return -_character.capsule_height() / 2.0
	return CAPSULE_HALF_HEIGHT_DOWN

func _model_path(is_person: bool, is_can: bool, team: int) -> String:
	if is_person:
		return PERSON_MODELS[team % PERSON_MODELS.size()]
	return CAN_VISUAL if is_can else TSINELAS_VISUAL

## Each mesh gets its OWN material via a surface override. Without this, every
## unit sharing a model would share one material resource, and flashing one of
## them white would flash all of them — including the enemy's.
## M-4: also handles ShaderMaterial (toon shader surfaces on Props).
## ⚠️ 7.1: the test is now `flash_amount`, not `albedo_color`. The outline
## next_pass shader carries neither, so it is still excluded — but the check now
## asks the question it actually means ("does this material take part in
## flashing?") instead of a colour uniform that happened to correlate.
func _collect_meshes(model: Node3D) -> void:
	for node in model.find_children("*", "MeshInstance3D", true, false):
		var mesh_instance := node as MeshInstance3D
		for surface in range(mesh_instance.get_surface_override_material_count()):
			var source: Material = mesh_instance.get_active_material(surface)
			if source is ShaderMaterial:
				var shader_mat := source as ShaderMaterial
				if shader_mat.get_shader_parameter("flash_amount") == null:
					continue
				var duped := shader_mat.duplicate() as ShaderMaterial
				mesh_instance.set_surface_override_material(surface, duped)
				_shader_materials.append(duped)
			elif source is BaseMaterial3D:
				# Typed as BaseMaterial3D, not StandardMaterial3D: a glTF surface can
				# import as ORMMaterial3D, and casting to StandardMaterial3D yields
				# null — which makes the renderer spew "Parameter 'material' is null".
				var mat := (source as BaseMaterial3D).duplicate() as BaseMaterial3D
				mesh_instance.set_surface_override_material(surface, mat)
				_materials.append(mat)
				_base_albedos.append(mat.albedo_color)

## M-4: replaces every surface material on `model` with a toon ShaderMaterial,
## then chains an inverted-hull outline as next_pass. Called in apply() before
## _collect_meshes() so the toon materials are what _collect_meshes() duplicates.
## Skipped for Persons — their glTF ORMMaterial3D stays until M-5 reskins them.
func _apply_toon_pass(model: Node3D, is_person: bool) -> void:
	if is_person:
		return
	var outline_mat := ShaderMaterial.new()
	outline_mat.shader = OUTLINE_SHADER
	for node in model.find_children("*", "MeshInstance3D", true, false):
		var mesh_instance := node as MeshInstance3D
		for surface in range(mesh_instance.get_surface_override_material_count()):
			var toon_mat := ShaderMaterial.new()
			toon_mat.shader = TOON_SHADER
			var original: Material = mesh_instance.get_active_material(surface)
			if original is BaseMaterial3D:
				var base_mat := original as BaseMaterial3D
				toon_mat.set_shader_parameter("albedo_color", base_mat.albedo_color)
				# Checklist 7.1 — CARRY THE TEXTURE ACROSS, do not drop it.
				# A generated .obj prop has no albedo texture and its colour is a
				# flat Kd, so this is a no-op for everything that shipped before
				# the kit overhaul. A Kenney kit mesh is textured off one shared
				# palette atlas, and without this the toon pass replaced that
				# atlas with a single flat colour — the whole model rendering as
				# one shade. See toon.gdshader's own header.
				var albedo_tex := base_mat.albedo_texture
				if albedo_tex != null:
					toon_mat.set_shader_parameter("albedo_texture", albedo_tex)
					toon_mat.set_shader_parameter("use_texture", true)
			elif original is ShaderMaterial:
				var orig_albedo = (original as ShaderMaterial).get_shader_parameter("albedo_color")
				if orig_albedo != null:
					toon_mat.set_shader_parameter("albedo_color", orig_albedo as Color)
			toon_mat.next_pass = outline_mat
			mesh_instance.set_surface_override_material(surface, toon_mat)

## Kenney's rig ships 32 clips. Without one playing, the model stands in its
## bind pose — a T-pose, which reads as broken art rather than as a character.
## Only "idle" is wired for now; walk/run blending is a separate task (see the
## follow-up noted in docs/Handoff.md item 18).
func _play_idle(model: Node3D) -> void:
	_animator = model.find_child("AnimationPlayer", true, false) as AnimationPlayer
	if _animator == null:
		return
	if not _animator.animation_finished.is_connected(_on_animation_finished):
		_animator.animation_finished.connect(_on_animation_finished)
	_play_locomotion()

## Kenney's rig ships 32 clips and only `idle` was ever wired, so a Person slid
## around the arena frozen in its rest pose — which reads as broken art more
## loudly than any modelling flaw. Picks the clip from actual horizontal speed.
##
## Driven from _process rather than from a signal because velocity is a
## continuously-varying value, not an event. `CharacterBase` is not told any of
## this: it owns the velocity, this file owns what the velocity looks like.
func _play_locomotion() -> void:
	if _animator == null or _character == null or _action_clip != "":
		return
	var speed := Vector2(_character.velocity.x, _character.velocity.z).length()
	var wanted := "idle"
	# ⚠️ B-90 — CARRY_IDLE_CLIP now wins over walk/sprint OUTRIGHT, checked
	# before speed at all, not just when standing still. It used to be the
	# opposite: "the rig has no holding-right-walk, and plain walk with the
	# slipper tracking the arm bone reads fine" — it does not. `carrier.gd`'s
	# `_step_carried()` snaps the carried unit to wherever the arm BONE
	# currently is every physics frame, and `camera_rig.gd`'s FPP viewmodel
	# arm chases that same live position — so the moment locomotion switches
	# to `walk`/`sprint`, the arm bone starts swinging through its walk cycle
	# and drags the held slipper (and the viewmodel arm chasing it) through
	# that swing. Reported: "my arms float during windup and when i run while
	# holding". The rig genuinely has no holding-right-walk clip to blend to
	# instead, so the fix is to stop trying to walk-animate a carrying arm at
	# all: legs stop swinging while holding something and moving, which is a
	# far smaller visual cost than the hand and viewmodel swimming every step.
	# ⚠️ 7.7 — DOWNED and AIRBORNE ARE CHECKED BEFORE ANYTHING ELSE, and in that
	# order, because both are states the game already tracks and neither had any
	# body language at all. The Kenney rig ships 32 clips and only eight were
	# wired; these are two of the four that map onto existing state.
	#
	# `die` on DOWNED: being knocked down read ONLY in the HUD flash and the
	# `Visual` tilt. A downed unit and a standing one played the same idle.
	#
	# `jump`/`fall` on airborne: `_play_locomotion()` selected on HORIZONTAL
	# speed alone, so a Person at the top of a jump — horizontal speed near zero —
	# played `idle`, and one moving sideways through the air played `walk`. Every
	# unit in this game can jump (§0's pillar put it on the Prop too), so that was
	# the most-seen missing pose in the build. Split by vertical velocity so a
	# rising jump and a falling one are not the same pose.
	#
	# ⚠️ NO NEW STATE, NO NEW INPUT, NO NEW NETWORKING. Every branch reads
	# something `character_base.gd` already owns and already replicates. That is
	# what keeps animation work in the design lane.
	if _character.state == CharacterBase.State.DOWNED:
		wanted = "die"
	elif not _character.is_on_floor():
		wanted = "jump" if _character.velocity.y > 0.0 else "fall"
	elif _is_holding():
		wanted = CARRY_IDLE_CLIP
	elif speed > RUN_SPEED_THRESHOLD:
		wanted = "sprint"
	elif speed > WALK_SPEED_THRESHOLD:
		wanted = "walk"
	if not _animator.has_animation(wanted):
		wanted = "idle"
	if _animator.has_animation(wanted) and _animator.current_animation != wanted:
		_animator.play(wanted)

func _process(delta: float) -> void:
	_play_locomotion()
	_spin_while_airborne(delta)
	_drive_viewmodel_charge()
	_process_remote_smoothing(delta)

## 4.2 — lags this node's position/rotation.y behind the body's own (already
## snapped) global position/yaw, for a remote character only. Explicitly
## skipped, and left at zero offset, for:
##   - the locally-driven character — client-authoritative and already smooth;
##     smoothing it adds pure input latency for no gain.
##   - anything not actually networked (Local Match / solo test) — there are
##     no remote peers to smooth against.
##   - a CARRIED or FLYING slipper — carriable.gd recomputes both identically
##     and deterministically on every peer, every physics frame, at zero
##     bandwidth. Lagging an already-agreed transform on top would make it
##     visibly trail the hand or the arc instead of matching it.
## rotation.x (airborne spin) and rotation.z (downed tilt) are untouched —
## only .y is this function's to write.
func _process_remote_smoothing(delta: float) -> void:
	if not _should_smooth_remote():
		if _smoothing_initialized:
			position = Vector3.ZERO
			rotation.y = 0.0
			_smoothing_initialized = false
		return
	if not _smoothing_initialized:
		snap_remote_transform()
		return

	var body_pos := _character.global_position
	var body_yaw := _character.rotation.y
	var t: float = 1.0 - exp(-REMOTE_SMOOTH_RATE * delta)
	_smoothed_world_pos = _smoothed_world_pos.lerp(body_pos, t)
	_smoothed_yaw = lerp_angle(_smoothed_yaw, body_yaw, t)

	# `position`/`rotation` here are always relative to the PARENT (the body),
	# so the world-space gap has to be rotated into the body's own frame —
	# otherwise "lagging behind" would read as the wrong direction the moment
	# the body itself turns.
	var world_gap := _smoothed_world_pos - body_pos
	position = _character.global_transform.basis.inverse() * world_gap
	rotation.y = wrapf(_smoothed_yaw - body_yaw, -PI, PI)

func _should_smooth_remote() -> bool:
	if _character == null or not NetworkManager.is_networked():
		return false
	if _character.is_multiplayer_authority():
		return false
	var carriable := _character.get_node_or_null("Carriable") as Carriable
	return carriable == null or not carriable.drives_movement()

## Resets the smoothing state to "caught up, right now" — called whenever the
## body's position was just TELEPORTED rather than walked (a round reset, a
## KillPlane respawn), so the visual snaps to the new spot instead of gliding
## across the map from wherever the last round/fall left it
## (Agent_Prompts.md §3). Safe to call even when smoothing is inactive; it
## just primes the state for whenever it next becomes active.
func snap_remote_transform() -> void:
	if _character == null:
		return
	_smoothed_world_pos = _character.global_position
	_smoothed_yaw = _character.rotation.y
	position = Vector3.ZERO
	rotation.y = 0.0
	_smoothing_initialized = true

## Feeds live charge power to the first-person viewmodel so the throwing arm
## visibly cocks back the longer the player holds. In first person the wind-up is
## the only readout of throw strength that is actually in the player's eyeline —
## the HUD's charge meter lives on the YOU card in a bottom corner, which nobody
## watches while aiming at a can.
##
## Polled, not signal-driven, for the reason _spin_while_airborne already
## documents: charge is a continuously-varying value, not an event, and a poll
## is self-healing across the model rebuild that every round swap performs.
func _drive_viewmodel_charge() -> void:
	if _character == null or not _character.is_person:
		return
	var rig := _character.get_node_or_null("CameraRig") as CameraRig
	if rig == null:
		return
	var carrier := _character.get_node_or_null("Carrier") as Carrier
	if carrier == null:
		return
	rig.set_viewmodel_charge(carrier.charge_power() if carrier.is_charging() else -1.0)

## Task 0 — the moodboard's THE SLIPPER card asks for "thrown trajectory (spin +
## motion blur)", and a slipper that flies without tumbling reads as a floating
## brick. Rate comes from the slipper's own ThrowProfile, so a wooden bakya
## tumbles lazily and a flip-flop whirls.
##
## POLLED from _process rather than driven off Carriable's carry_state_changed
## signal, deliberately. Spin is a continuous per-frame value, not an event —
## same reasoning _play_locomotion already documents for reading velocity. It
## also sidesteps a sibling-ready ordering question: Carriable and this node are
## both children of CharacterBase, and nothing guarantees which is ready first.
func _spin_while_airborne(delta: float) -> void:
	if _character == null:
		return
	var carriable: Carriable = _character.get_node_or_null("Carriable") as Carriable
	if carriable == null:
		return
	if carriable.state != Carriable.CarryState.FLYING:
		# Land flat. Not an else-branch on a tween: a slipper that stops spinning
		# mid-tumble and freezes at 37° looks like a physics bug.
		if rotation.x != 0.0:
			rotation.x = 0.0
		return
	rotation.x += deg_to_rad(carriable.spin_speed_deg()) * delta

## Whether this Person currently has something in their hand. Asked of the
## Carrier component (the holder's side), not of Carriable (the held thing's
## side) — this node belongs to the Person.
func _is_holding() -> bool:
	if _character == null or not _character.is_person:
		return false
	var carrier := _character.get_node_or_null("Carrier") as Carrier
	if carrier == null:
		return false
	# The public accessor, not the private field. carrier.gd exposes held() for
	# exactly this, and reaching past it with get("_held") would break silently
	# the day that field is renamed.
	return carrier.held() != null

## Plays a one-shot action clip — the visible half of "their arms move when they
## grab". Called by `character_base.gd` when an ability or a bump fires. Falls
## back through the roster in order, since not every clip exists on every model,
## and no-ops entirely on a Can or a Tsinelas (neither has an AnimationPlayer).
func play_action(kind: String) -> void:
	# Playtest 0.4: "make sure ur hand actually moves/animates when in interact
	# like throw". The third-person model has always animated here; in FIRST
	# person the player sees the viewmodel instead, and it was static. Driven
	# from this one call site rather than from the input code so the two views
	# can never disagree about whether a throw happened — and deliberately
	# BEFORE the `_animator == null` early-out below, because a Prop has no
	# AnimationPlayer and would otherwise return before the rig is told.
	var rig := _character.get_node_or_null("CameraRig") as CameraRig if _character != null else null
	if rig != null:
		rig.play_viewmodel_action(kind)

	if _animator == null:
		return
	var candidates: Array[String] = ACTION_CLIPS.get(kind, [] as Array[String])
	for clip in candidates:
		if _animator.has_animation(clip):
			_action_clip = clip
			_animator.play(clip)
			return

func _on_animation_finished(anim_name: StringName) -> void:
	# Hand control back to locomotion once the one-shot is done, otherwise the
	# character freezes on the last frame of its throw.
	if String(anim_name) == _action_clip:
		_action_clip = ""
		_play_locomotion()

## B-44: brief white flash on a landed hit, on every mesh this unit has.
## Q-8: also bursts impact particles — see _spawn_impact_particles below.
## M-4: also flashes ShaderMaterial (toon) surfaces on Props via set_shader_parameter.
func flash_hit() -> void:
	_spawn_impact_particles()
	if _materials.is_empty() and _shader_materials.is_empty():
		return
	if _flash_tween != null and _flash_tween.is_valid():
		_flash_tween.kill()
	_flash_tween = create_tween().set_parallel(true)
	for i in range(_materials.size()):
		_materials[i].albedo_color = Color.WHITE
		_flash_tween.tween_property(_materials[i], "albedo_color", _base_albedos[i], FLASH_DURATION)
	# ⚠️ 7.1: this drives `flash_amount`, NOT `albedo_color`. Tweening the colour
	# uniform cannot work on a textured kit mesh — its resting tint is white, so
	# "flash to white" is a no-op and a hit on a kit prop showed nothing at all.
	# The flash is its own uniform now; `albedo_color` means only "what colour am
	# I", which is what it should always have meant.
	for mat in _shader_materials:
		mat.set_shader_parameter("flash_color", Color.WHITE)
		mat.set_shader_parameter("flash_amount", 1.0)
		_flash_tween.tween_method(
			func(a: float) -> void: mat.set_shader_parameter("flash_amount", a),
			1.0, 0.0, FLASH_DURATION)

## Q-8: one-shot burst, no art asset — a primitive point mesh + unshaded
## StandardMaterial3D in UiTheme.IMPACT, matching the moodboard's "IMPACT
## EFFECT (particle burst)". Frees itself once spent rather than leaking one
## GPUParticles3D node per hit for the rest of the match.
func _spawn_impact_particles() -> void:
	var material := ParticleProcessMaterial.new()
	material.direction = Vector3(0, 1, 0)
	material.spread = 180.0 ## spherical emission
	material.initial_velocity_min = 1.5
	material.initial_velocity_max = 3.5
	material.gravity = Vector3(0, -9.8, 0)
	material.color = UiTheme.IMPACT

	var point_mesh := SphereMesh.new()
	point_mesh.radius = 0.04
	point_mesh.height = 0.08
	var point_material := StandardMaterial3D.new()
	point_material.albedo_color = UiTheme.IMPACT
	point_material.shading_mode = BaseMaterial3D.SHADING_MODE_UNSHADED
	point_mesh.material = point_material

	var particles := GPUParticles3D.new()
	particles.emitting = false
	particles.one_shot = true
	particles.explosiveness = 1.0 ## a burst, not a stream
	particles.amount = IMPACT_PARTICLE_COUNT
	particles.lifetime = IMPACT_PARTICLE_LIFETIME
	particles.process_material = material
	particles.draw_pass_1 = point_mesh
	particles.position.y = IMPACT_PARTICLE_HEIGHT
	particles.finished.connect(particles.queue_free)
	add_child(particles)
	particles.emitting = true

## Q-6: a Guard blocking a hit had no feedback at all. Deliberately
## DEFENSE-tinted rather than white, so a blocked hit is never mistaken for a
## landed one (flash_hit() above) at a glance.
## M-4: also flashes ShaderMaterial (toon) surfaces on Props.
func flash_blocked() -> void:
	if _materials.is_empty() and _shader_materials.is_empty():
		return
	if _flash_tween != null and _flash_tween.is_valid():
		_flash_tween.kill()
	_flash_tween = create_tween().set_parallel(true)
	for i in range(_materials.size()):
		_materials[i].albedo_color = UiTheme.DEFENSE
		_flash_tween.tween_property(_materials[i], "albedo_color", _base_albedos[i], FLASH_DURATION)
	# Same split as flash_hit(); `flash_color` is what keeps a block visually
	# distinct from a landed hit (Q-6) now that the amount is separate.
	for mat in _shader_materials:
		mat.set_shader_parameter("flash_color", UiTheme.DEFENSE)
		mat.set_shader_parameter("flash_amount", 1.0)
		_flash_tween.tween_method(
			func(a: float) -> void: mat.set_shader_parameter("flash_amount", a),
			1.0, 0.0, FLASH_DURATION)
