extends Node
class_name AudioManagerScript
## Registered as the "AudioManager" autoload singleton (Project Settings > Autoload).
## Referenced globally as `AudioManager`, e.g. `AudioManager.play_at("bump", pos)`.

## Checklist 4.1 — the whole audio workstream's entry point. Before this, the
## repository contained ZERO AudioStreamPlayers of any kind: a lata could take a
## direct hit in complete silence, which reads as a broken build rather than as
## a missing feature.
##
## WHAT THIS OWNS
##   * The name -> stream table (SFX). One line per sound; see SFX_PATHS.
##   * Two voice pools, so nothing in gameplay ever calls `Node.new()` on a hot
##     path (a hit can resolve several times a frame — see the retrigger note).
##   * The three-bus volume model (Master / SFX / Music), driven by
##     SettingsManager and persisted to user://settings.cfg.
##
## WHAT THIS DELIBERATELY DOES NOT OWN
##   Map ambience. Those are plain looping AudioStreamPlayer nodes authored into
##   each map scene by its generator (tools/maps/build_*.py), on the Music bus,
##   because ambience is part of a place and belongs to that place's scene — the
##   same rule that put the WorldEnvironment and the kill plane in the map
##   rather than in Main.tscn (see main.gd::_load_map).
##
## ---------------------------------------------------------------------------
## ⚠️ THE AUDIO CLOCK IS NOT THE GAME CLOCK, AND THAT IS LOAD-BEARING HERE.
## ---------------------------------------------------------------------------
## `CharacterBase._hitstop()` dips `Engine.time_scale` to 0.05 for 60 ms on every
## landed hit (4.5). That scales `delta`, `SceneTreeTimer`, and every tween — but
## NOT the audio server, which runs on real time and does not repitch. That is
## exactly what makes a frame-synced impact work: the picture freezes and the
## clang plays at full speed and full pitch straight through it.
##
## It is also why every timing decision in this file uses
## `Time.get_ticks_msec()` (real milliseconds) and never `delta` or
## `create_timer`. A retrigger guard measured in scaled time would stretch 20x
## during hitstop — i.e. exactly during the moment it is guarding.

## Voices for non-positional audio: UI, and anything the local player should
## hear at a fixed volume regardless of where it happened (round win, countdown).
const UI_VOICES: int = 8
## Voices for positional gameplay audio. 12 is sized for the worst realistic
## frame: four units, two of them being hit, an ability firing and a slipper
## landing. Past that the oldest voice is stolen, which is the correct failure —
## a dropped sound is better than an allocation spike mid-fight.
const WORLD_VOICES: int = 12

## Default 3D falloff. The arena's playable width is ~17 units (Bounds/Wall* sit
## at ±8.6) and the confinement box is 5.0, so a 30-unit max distance means
## everything in the arena is audible and nothing outside it intrudes. Unit size
## rather than max distance is what actually shapes the curve in Godot 4.
const WORLD_UNIT_SIZE: float = 12.0
const WORLD_MAX_DISTANCE: float = 30.0

## ⚠️ THIS IS NOT COSMETIC — IT IS WHAT STOPS THE IMPACT BECOMING A BUZZSAW.
##
## `hitbox.gd::_on_area_entered` is re-run every physics frame for the whole of
## a thrown slipper's flight (`carriable.gd::_step_flying` calls
## `sweep_hitbox()` deliberately, because `area_entered` only fires on the ENTER
## edge and would otherwise miss a can already inside the hitbox on frame one).
## A slipper resting against a lata therefore resolves a "hit" 60 times a second.
## The state machine absorbs that fine — `apply_stagger` no-ops on a DOWNED or
## SEALED target — and `_hitstop()` has its own static guard, so nobody noticed.
## Audio does not absorb it on its own: a fixed 60 ms floor only throttles the
## TRIGGER rate, and `lata_impact` itself RINGS for ~300 ms — so sustained
## contact still stacked up to 5 overlapping, pitch-jittered copies of the same
## clang, which is what the "continuous metallic scream" actually sounded like
## in practice even with the floor in place. Fixed below by keying the guard to
## each sound's own ring time instead of one constant, so at most one voice of
## a given name is ever ringing at once. See `_retrigger_window()`.
##
## Measured in REAL milliseconds, per sound name. 60 ms is one hitstop, and is
## kept only as a floor — see `_retrigger_window()` for where the real,
## per-sound window comes from.
const RETRIGGER_MS: int = 60

## Pitch jitter applied to every play, as a fraction. Four players hitting things
## in a party game produce the same sound dozens of times a round; without this
## it reads as a looping sample rather than as impacts. Excluded for UI and for
## the match-state fanfares, which are melodic and must not detune (see
## `_NO_JITTER`).
const PITCH_JITTER: float = 0.07

const SFX_DIR: String = "res://assets/audio/sfx/"

## Every sound in the game. Generated by tools/audio/generate_sfx.py — that
## script's section headers explain what each one is trying to sound like and
## why. Adding a sound is one line HERE and one function there; nothing else in
## the codebase needs to learn about it.
const SFX_NAMES: PackedStringArray = [
	# The lata — the sounds the whole game is built around.
	"lata_impact", "lata_knockdown", "lata_seal",
	"reset_channel_start", "reset_channel_complete",
	# Bodies.
	"bump", "tag", "downed", "jump", "land", "dash", "guard_block", "respawn",
	# The slipper.
	"throw_whoosh", "throw_charge", "slipper_land", "slipper_bounce", "grab",
	# Abilities (checklist 4.1's per-ability set).
	"ability_bagsak_bomb", "ability_bakya_bash", "ability_flick_dash",
	"ability_shatter_trap", "ability_spin_guard",
	# Match state.
	"countdown_tick", "countdown_go", "round_win", "round_lose", "match_win",
	# UI.
	"ui_click", "ui_hover", "ui_back", "ui_error",
]

## Sounds that must never be pitch-jittered: anything with a tune in it. A
## detuned UI click is unnoticeable; a detuned victory fanfare sounds broken.
const _NO_JITTER: PackedStringArray = [
	"ui_click", "ui_hover", "ui_back", "ui_error",
	"countdown_tick", "countdown_go", "round_win", "round_lose", "match_win",
]

## Per-sound level trim, applied on top of the bus. Anything not listed plays at
## 0 dB. This is mix balance, not a volume control — the player's own sliders are
## the bus volumes below.
const _TRIM_DB: Dictionary = {
	"lata_impact": 1.5,      # the single most important sound in the game
	"lata_seal": 1.0,
	"match_win": 1.0,
	"ui_hover": -8.0,        # fires on every mouse move across a menu
	"ui_click": -3.0,
	"slipper_bounce": -4.0,
	"land": -6.0,            # fires constantly; must sit under everything
	"jump": -4.0,
	"throw_charge": -5.0,
}

var _streams: Dictionary = {}          ## name -> AudioStream
## name -> real-ms retrigger window for that sound. See `_retrigger_window()`.
var _retrigger_ms: Dictionary = {}
var _ui_voices: Array[AudioStreamPlayer] = []
var _world_voices: Array[AudioStreamPlayer3D] = []
var _ui_next: int = 0
var _world_next: int = 0
## name -> Time.get_ticks_msec() of its last play. See RETRIGGER_MS.
var _last_played_ms: Dictionary = {}

## 0..1, mirrored from SettingsManager (which owns persistence). Kept here too so
## the bus state and the saved state can be compared without reaching across.
var master_volume: float = 1.0
var sfx_volume: float = 1.0
var music_volume: float = 1.0


func _ready() -> void:
	# ⚠️ PROCESS_MODE_ALWAYS, and the voices below inherit it.
	#
	# The pause overlay (B-20) sets `get_tree().paused = true`, and a paused
	# AudioStreamPlayer stops dead. Without this, every button in the pause menu
	# — including the Settings panel where the volume sliders live — would be
	# silent, so dragging the SFX slider would produce no audible feedback at
	# exactly the moment the player is trying to set it by ear.
	process_mode = Node.PROCESS_MODE_ALWAYS
	_load_streams()
	_build_voices()


## Loads every entry in SFX_NAMES. A missing file warns once and is then simply
## absent — `play()` no-ops on an unknown name rather than erroring, so a
## half-generated assets/audio/sfx/ can never crash a match.
func _load_streams() -> void:
	for sound_name in SFX_NAMES:
		var path := SFX_DIR + sound_name + ".wav"
		if not ResourceLoader.exists(path):
			push_warning("AudioManager: missing '%s' — run tools/audio/generate_sfx.py" % path)
			continue
		var stream := load(path) as AudioStream
		if stream == null:
			push_warning("AudioManager: '%s' did not load as an AudioStream" % path)
			continue
		_streams[sound_name] = stream
		_retrigger_ms[sound_name] = _retrigger_window(stream)


func _build_voices() -> void:
	for i in UI_VOICES:
		var player := AudioStreamPlayer.new()
		player.bus = &"SFX"
		player.process_mode = Node.PROCESS_MODE_ALWAYS
		add_child(player)
		_ui_voices.append(player)
	for i in WORLD_VOICES:
		var player := AudioStreamPlayer3D.new()
		player.bus = &"SFX"
		player.process_mode = Node.PROCESS_MODE_ALWAYS
		player.unit_size = WORLD_UNIT_SIZE
		player.max_distance = WORLD_MAX_DISTANCE
		# Linear rather than the inverse-square default: an arena this small
		# with an inverse-square curve is either deafening at the base circle or
		# inaudible at the throwing line, and there is no unit size that is both.
		player.attenuation_model = AudioStreamPlayer3D.ATTENUATION_INVERSE_DISTANCE
		add_child(player)
		_world_voices.append(player)


## ---------------------------------------------------------------------------
## PLAYBACK
## ---------------------------------------------------------------------------

## Non-positional. Use for UI, and for anything the local player must hear at a
## constant level wherever it happened — round/match results, the countdown.
func play(sound_name: String, volume_db: float = 0.0) -> void:
	var stream: AudioStream = _take(sound_name)
	if stream == null:
		return
	var player := _ui_voices[_ui_next]
	_ui_next = (_ui_next + 1) % _ui_voices.size()
	player.stream = stream
	player.volume_db = volume_db + _trim(sound_name)
	player.pitch_scale = _pitch(sound_name)
	player.play()


## Positional. Everything that happens at a place in the arena goes through
## here, so a hit across the map reads as distance rather than as a sound in
## your ear.
##
## `where` is a WORLD position. Callers pass `character.global_position`
## directly; there is deliberately no overload that takes a Node, because a
## transient hitbox's node is routinely freed before its sound has finished and
## parenting audio to it would cut the sound off mid-clang.
func play_at(sound_name: String, where: Vector3, volume_db: float = 0.0) -> void:
	var stream: AudioStream = _take(sound_name)
	if stream == null:
		return
	var player := _world_voices[_world_next]
	_world_next = (_world_next + 1) % _world_voices.size()
	player.stream = stream
	player.global_position = where
	player.volume_db = volume_db + _trim(sound_name)
	player.pitch_scale = _pitch(sound_name)
	player.play()


## Shared front half of play()/play_at(): resolves the stream and applies the
## retrigger guard. Returns null when this call should be dropped.
func _take(sound_name: String) -> AudioStream:
	var stream: AudioStream = _streams.get(sound_name)
	if stream == null:
		return null
	# Real milliseconds, NOT delta — see the class doc's audio-clock note.
	var window: int = int(_retrigger_ms.get(sound_name, RETRIGGER_MS))
	var now := Time.get_ticks_msec()
	if now - int(_last_played_ms.get(sound_name, -window)) < window:
		return null
	_last_played_ms[sound_name] = now
	return stream


## The real fix for the buzzsaw case (see the ⚠️ note above RETRIGGER_MS): the
## guard has to keep the PREVIOUS voice of this same sound from still being
## audible when a new one starts, not just space out how often a new one is
## allowed to begin. Using the stream's own length means the window scales with
## what it's actually guarding — a 300 ms clang gets ~300 ms, a 40 ms UI tick
## gets ~40 ms — instead of one number that was only ever right for whichever
## sound it was tuned against.
##
## RETRIGGER_MS is kept as a floor, not dropped: `AudioStream.get_length()` can
## come back at or near 0 for a degenerate/corrupt asset, and this guard's
## other job — collapsing the two calls `_flash_hit()`/`_rpc_play_hit_vfx` can
## produce for the same hit inside a single frame (see character_base.gd) — is
## a same-frame guard that still needs to hold regardless.
func _retrigger_window(stream: AudioStream) -> int:
	var length_ms := int(roundf(stream.get_length() * 1000.0))
	return maxi(RETRIGGER_MS, length_ms)


func _trim(sound_name: String) -> float:
	return _TRIM_DB.get(sound_name, 0.0)


func _pitch(sound_name: String) -> float:
	if sound_name in _NO_JITTER:
		return 1.0
	return randf_range(1.0 - PITCH_JITTER, 1.0 + PITCH_JITTER)


## ---------------------------------------------------------------------------
## BUS VOLUMES — the Settings panel's three sliders land here.
## ---------------------------------------------------------------------------
##
## SettingsManager owns the values and their persistence; this owns what they
## mean to the mixer. Split that way so the volume model can change (a fourth
## bus, a compressor on Master) without touching the settings file format.

## Called by SettingsManager on load and on every slider move. All three are
## 0..1 linear.
func apply_volumes(master: float, sfx: float, music: float) -> void:
	master_volume = clampf(master, 0.0, 1.0)
	sfx_volume = clampf(sfx, 0.0, 1.0)
	music_volume = clampf(music, 0.0, 1.0)
	_apply_bus("Master", master_volume)
	_apply_bus("SFX", sfx_volume)
	_apply_bus("Music", music_volume)


## ⚠️ MUTES AT ZERO RATHER THAN TRUSTING linear_to_db(0.0).
##
## `linear_to_db(0.0)` is -INF, and assigning that to a bus volume is undefined
## rather than silent — depending on the mixer path it is either -80 dB (audible
## in a quiet room, so "off" is not off) or a NaN that poisons the bus. An
## explicit mute is the only way a slider dragged to the left end is actually
## silence. The threshold is a slider step below the minimum, not exactly 0.0,
## so a float that lands on 0.0009 still counts as off.
func _apply_bus(bus_name: String, linear: float) -> void:
	var index := AudioServer.get_bus_index(bus_name)
	if index < 0:
		push_warning("AudioManager: no '%s' bus — is default_bus_layout.tres registered "
			% bus_name + "in project.godot under audio/buses/default_bus_layout?")
		return
	if linear <= 0.001:
		AudioServer.set_bus_mute(index, true)
		return
	AudioServer.set_bus_mute(index, false)
	AudioServer.set_bus_volume_db(index, linear_to_db(linear))
