extends Node3D
class_name EnvToonPass

## Per-instance COLOUR for the map's dressing: seeded facade tints, recoloured
## roof atlases, foliage variation and the road's warm-neutral correction.
##
## ⚠️ IT NO LONGER APPLIES TOON SHADING OR OUTLINES, AND THE NAME IS A LEFTOVER.
## Phase 8 used this to put the whole map on toon.gdshader + an inverted-hull
## outline so world and characters shared one shading model. That shipped, was
## played, and was reverted on 2026-07-29: "the current shaders look terrible and
## are causing severe lag on other PCs. The toon shader is creating ugly,
## horizontal banded shadows." See _apply() for why both halves of that are
## structural rather than tuning. Characters keep their toon pass; the world is
## plainly lit and cheap.
##
## ⚠️ WHY THIS EXISTS AT ALL. `character_visual.gd::_apply_toon_pass()` was the
## only thing in the project that ever applied `toon.gdshader`, and it runs on
## characters and Props exclusively. Every house, tree, car, road tile and market
## stall therefore rendered with Kenney's imported `StandardMaterial3D` — full
## specular, standard diffuse — while every character next to them rendered
## `diffuse_toon` with `SPECULAR = 0.0`. The world and the actors were lit by two
## different shading models, which is a large part of why the map read as
## "sterile" and as though the characters were composited into it. It is also
## invisible in any screenshot of a character on its own, which is why it went
## unnoticed through a whole kit overhaul.
##
## Human call, 2026-07-29: "extend the toon pass to ALL map dressing and props.
## The world and actors must share the same shading model."
##
## ⚠️ THIS IS A VISUAL PASS AND NOTHING ELSE. It touches `surface_override_material`
## and reads `global_transform.basis`. It adds no state, no signal, no input, no
## group membership and no network traffic — a `Dressing` subtree is scenery, no
## peer replicates it, and `network_manager.gd` has never known it exists.
## Deliberately NOT `@tool`: running in the editor would bake override materials
## into the .tscn, and this file is generated by `tools/maps/build_eskinita.py`.

## ⚠️ NOTHING IN THE MAP GETS AN OUTLINE ANY MORE. Kept as an empty list rather
## than deleted so the call sites keep their shape if outlines ever come back for
## a hero prop. The inverted hull was half the map's draw calls for a border
## nobody could see past ~10m.
const NO_OUTLINE_GROUPS: Array[String] = ["Belt", "Road", "Layer1", "Layer2", "Layer3", "Clutter"]

## ⚠️ PAINT THE STREET. One kit atlas means one house, five hundred times.
##
## Human call, 2026-07-29, on seeing the first Phase 8 render: "dont use same
## green house for all, it looks so repetitive, try to make it more colorful but
## in a way that looks good and not messy."
##
## Every `building-type-*` in the City Kit samples the SAME shared `colormap.png`,
## so all 11 types ship with the same mint roof and the same off-white wall. No
## amount of type-cycling in the map generator fixes that — it varies the
## SILHOUETTE and cannot vary the COLOUR, which is why the street read as one
## house stamped down a hundred times.
##
## `toon.gdshader` multiplies `albedo_color` over the atlas, so a per-instance
## tint is the one lever that does vary colour, and it costs nothing: no new
## texture, no new material in the .tscn, no change to the generator.
##
## ⚠️ THE PALETTE IS `UiTheme`'s OWN `ENV_PAINT_*`, NOT INVENTED HERE, AND THAT
## IS WHAT KEEPS IT FROM LOOKING MESSY. Those four were already chosen as "the
## default Manila facade" set and are already documented as deliberately warm or
## desaturated-cool so they never approach OFFENSE #f87020 or DEFENSE #0080e8
## (Dev_Plan.md §4.2 rule 1 — the world is the largest surface in the frame, and
## a facade in a role hue eats the character silhouette). Adding a fifth colour
## here means adding it to UiTheme first and arguing for it there.
const FACADE_TINTS: Array[Color] = [
	Color("e2d2ac"),  ## ENV_PAINT_CREAM — the default Manila facade
	Color("b5664c"),  ## ENV_PAINT_TERRA — oxide red / terracotta
	Color("86b4a6"),  ## ENV_PAINT_MINT  — the pale mint that is everywhere
	Color("c9994a"),  ## ENV_PAINT_OCHRE — mustard
	Color("b7b2a6"),  ## ENV_CONCRETE    — unpainted, and every street has some
	Color("cbb9b4"),  ## a washed-out rose; the same family, one step cooler
]

## Foliage varies on the same principle as the facades. Every City Kit tree is
## the same swatch of the same atlas, and with a tree every few metres down both
## kerbs plus three belt rings of them, "all green" survived the roof fix purely
## on the trees. Kept inside a narrow green-to-olive range on purpose: varied
## FOLIAGE is a real street, multicoloured foliage is a fairground.
const FOLIAGE_TINTS: Array[Color] = [
	Color(0.86, 0.94, 0.78),
	Color(0.72, 0.82, 0.60),
	Color(0.95, 0.90, 0.66),
	Color(0.62, 0.76, 0.58),
	Color(0.80, 0.86, 0.70),
]

## ⚠️ THE ROAD IS BLUE IN THE ASSET, NOT IN THE LIGHTING, AND THIS IS WHERE IT IS
## FIXED. `kits/town/road` is a Fantasy Town cobble: its mesh has a single UV at
## (0.15625, 0.625), so the whole tile samples ONE texel, and that texel measures
## (160, 168, 201) — periwinkle. Paved wall-to-wall that turned the entire map
## lavender, which is not what "urban side street" looks like anywhere. Tinted to
## a warm neutral rather than retinted in the atlas, because that same texel is
## shared with other Fantasy Town pieces and moving it would drag them along.
const ROAD_TINT: Color = Color(0.66, 0.62, 0.55)

## The silhouette belt is 30-45 m out and exists to be READ, not looked at.
## Pulling it toward the fog colour makes it recede properly instead of sitting
## as a hard-edged colourful band behind the houses.
const BELT_FADE: Color = Color(0.878, 0.812, 0.694)
const BELT_FADE_AMOUNT: float = 0.68

## Which groups get a seeded facade tint at all. Clutter keeps its own authored
## colours — those meshes carry the project's palette already.
const FACADE_GROUPS: Array[String] = ["Layer1", "Layer2", "Belt"]

## ⚠️ ROOFS NEED A DIFFERENT LEVER FROM WALLS, AND THIS IS IT.
##
## `FACADE_TINTS` above multiplies the whole atlas, which varies the near-white
## WALL beautifully and does nothing for the roof: the roof swatch is a saturated
## green (#61CB8B) and green multiplied by any tint is still green. Measured, a
## City Kit building is ONE mesh with ONE primitive and ONE material, so there is
## no surface index to tint separately either.
##
## So the roof is recoloured in the TEXTURE, and `tools/models/make_roof_atlases.py`
## emits one atlas per roof colour from the shipped one. Swapping which atlas an
## instance samples is the only way to give two buildings different roofs when
## they share a mesh, a material and a shader.
##
## ⚠️ RUN `python tools/models/make_roof_atlases.py` IF THESE FAIL TO PRELOAD.
## They are generated files. They are committed, but a kit update that changes
## the roof swatch means regenerating them — the tool fails loudly in that case
## rather than emitting five identical atlases.
const ROOF_ATLASES: Array[Texture2D] = [
	preload("res://assets/models/kits/city/Textures/colormap_roof_terra.png"),
	preload("res://assets/models/kits/city/Textures/colormap_roof_rust.png"),
	preload("res://assets/models/kits/city/Textures/colormap_roof_slate.png"),
	preload("res://assets/models/kits/city/Textures/colormap_roof_ochre.png"),
	preload("res://assets/models/kits/city/Textures/colormap_roof_jade.png"),
]

## Hung cloth sways; nothing else does. Matched to `env_kit.gd::_laundry_line()`:
## the wire hangs at local y 2.62 and the longest garment drops 0.70 below it, so
## these are the mesh's own numbers rather than a tuned guess. A vertex at the
## wire itself gets drop = 0 and does not move, which is what keeps the line
## looking pinned to the buildings.
const WIND_PREFIX: String = "Sampay"
const WIND_STRENGTH: float = 0.075
const WIND_SPEED: float = 1.15
const WIND_ANCHOR_Y: float = 2.62
const WIND_DROP: float = 0.70

## Belt geometry is the single largest instance count on the map and none of it
## is ever approached. Skipping the second (inverted-hull) draw call for it is
## also most of this pass's frame-time budget back.
func _ready() -> void:
	for child in get_children():
		var layer := child as Node3D
		if layer == null:
			continue
		var outlined := not NO_OUTLINE_GROUPS.has(layer.name)
		var facaded := FACADE_GROUPS.has(layer.name)
		for node in layer.find_children("*", "MeshInstance3D", true, false):
			var mesh_instance := node as MeshInstance3D
			# The wind flag is decided from the INSTANCE's own name, not the
			# mesh's, because a kit piece's inner MeshInstance3D is named by
			# Kenney. Walk up to whichever ancestor the map generator named.
			var tint := Color.WHITE
			var roof: Texture2D = null
			var owner_name := _instance_name(mesh_instance, layer)
			if layer.name == "Road":
				tint = ROAD_TINT
			elif facaded:
				# ⚠️ CLASSIFY BY THE GENERATOR'S OWN NAME. "Is this a building?"
				# cannot be answered from the mesh: Layer1 holds houses AND parked
				# cars, Layer2 holds houses AND street trees, and the Belt holds
				# both again. The first version keyed off the LAYER instead and
				# handed a City Kit roof atlas to every van in the street — cars
				# are textured off the CAR atlas, so pointing their UVs at a city
				# colormap makes them sample whatever happens to sit at those
				# coordinates. Verified by dumping the per-instance texture, not
				# by looking at a render, because a wrongly-atlased car still
				# renders perfectly happily in some plausible colour.
				if _is_building(owner_name):
					tint = _facade_tint(owner_name)
					roof = _roof_atlas(owner_name)
				elif owner_name.contains("Tree"):
					# Foliage varies too — otherwise a hundred identical green
					# cones is the same repetition complaint as the roofs, and
					# the trees are what is actually left reading as "all green".
					tint = FOLIAGE_TINTS[(_name_hash(owner_name) * 11 + 3)
						% FOLIAGE_TINTS.size()]
				# Everything else in these layers (parked cars) keeps its kit
				# colours untouched. A car is small, already varied by model, and
				# is the one thing on the street that is SUPPOSED to be a bright
				# manufactured colour.
				if layer.name == "Belt":
					tint = tint.lerp(BELT_FADE, BELT_FADE_AMOUNT)
			_apply(mesh_instance, outlined, _wants_wind(mesh_instance, layer),
				tint, roof)


## The map generator's building names, and nothing else. Layer1/Layer2 rows are
## `L1_<i>_<side>` / `L2_<i>`, the silhouette belt is `BeltX_<i>` / `BeltZ_<i>`,
## and its trees are `BeltTreeX_<i>` / `BeltTreeZ_<i>` — which is why this checks
## the belt prefixes BEFORE falling through, or every belt tree would match.
func _is_building(instance_name: String) -> bool:
	if instance_name.begins_with("BeltTree"):
		return false
	return (instance_name.begins_with("L1_")
		or instance_name.begins_with("L2_")
		or instance_name.begins_with("BeltX_")
		or instance_name.begins_with("BeltZ_"))


## The name the MAP GENERATOR gave this instance ("L1_7_E", "BeltX_31"), not the
## name Kenney gave the MeshInstance3D inside it. Tinting by the inner name would
## give every building that shares a mesh the same colour, which is the exact
## repetition this is here to break.
func _instance_name(node: Node, stop_at: Node) -> String:
	var walker: Node = node
	var last: String = node.name
	while walker != null and walker != stop_at:
		last = walker.name
		walker = walker.get_parent()
	return last


## ⚠️ SEEDED, NEVER RANDOM — the same rule the map generator works under.
## A street that repaints itself every time the scene loads cannot be reviewed in
## a screenshot and cannot be reproduced from a bug report. This hashes the
## instance's own stable name, so a given house is the same colour forever.
##
## The multiplier is prime-ish against the palette length so consecutive houses
## (L1_0, L1_1, L1_2 ...) never walk the palette in order, which would read as a
## repeating rainbow — messier than one colour, and the thing to avoid.
func _facade_tint(instance_name: String) -> Color:
	return FACADE_TINTS[(_name_hash(instance_name) * 7) % FACADE_TINTS.size()]


## ⚠️ A DIFFERENT MULTIPLIER FROM `_facade_tint`, ON PURPOSE.
## Seeded off the same name but stirred differently, so wall colour and roof
## colour are chosen independently. Sharing the multiplier would lock each wall
## to one roof and give six house types instead of the thirty the two palettes
## can actually make between them — which is the repetition complaint again,
## just one level up.
func _roof_atlas(instance_name: String) -> Texture2D:
	return ROOF_ATLASES[(_name_hash(instance_name) * 13 + 5) % ROOF_ATLASES.size()]


func _name_hash(text: String) -> int:
	var value := 0
	for i in text.length():
		value = (value * 31 + text.unicode_at(i)) & 0x7fffffff
	return value


func _wants_wind(node: Node, stop_at: Node) -> bool:
	var walker: Node = node
	while walker != null and walker != stop_at:
		if walker.name.begins_with(WIND_PREFIX):
			return true
		walker = walker.get_parent()
	return false


func _apply(mesh_instance: MeshInstance3D, outlined: bool, windy: bool,
		tint: Color, roof: Texture2D) -> void:
	# ⚠️ PLAIN StandardMaterial3D. NOT a ShaderMaterial, NOT an outline pass.
	#
	# Phase 8 put the whole map on toon.gdshader + the inverted-hull outline so
	# the world and the characters shared one shading model. Shipped and played,
	# it was the wrong call and the human called it: "the current shaders look
	# terrible and are causing severe lag on other PCs. The toon shader is
	# creating ugly, horizontal banded shadows."
	#
	# Both halves are real and both are structural, not tuning:
	#   * COST. Toon + outline is TWO draw calls and a unique ShaderMaterial per
	#     surface across ~510 dressing instances. The outline pass alone doubles
	#     the map's draw calls, and it buys nothing at 30m.
	#   * BANDING. `diffuse_toon` is a hard 2-band step. On the large, nearly-flat
	#     wall planes of a kit building, the terminator between those two bands
	#     lands as a wide horizontal stripe across the facade — which is exactly
	#     what "ugly horizontal banded shadows" describes. It reads fine on a
	#     small curved character and badly on a 12m wall.
	#
	# What survives is the part that was actually wanted: the seeded facade tint
	# and the roof-variant atlas, which is where the street's colour variety comes
	# from. Those are properties on a stock material and cost nothing.
	#
	# ⚠️ CHARACTERS KEEP THE TOON PASS. character_visual.gd is untouched — the
	# shading split this file was written to close is now deliberate: actors are
	# toon-shaded and readable, the world is plainly lit and cheap. That is the
	# normal arrangement for this art style and it is what "performance and visual
	# clarity are significantly more important than heavy effects" asks for.
	for surface in range(mesh_instance.get_surface_override_material_count()):
		var original: Material = mesh_instance.get_active_material(surface)
		var mat := StandardMaterial3D.new()
		mat.roughness = 1.0
		mat.metallic = 0.0
		mat.specular_mode = BaseMaterial3D.SPECULAR_DISABLED
		# Vertex colours are off on these kits; the atlas carries everything.
		if original is BaseMaterial3D:
			var base_mat := original as BaseMaterial3D
			mat.albedo_color = base_mat.albedo_color * tint
			var tex := base_mat.albedo_texture
			# A roof variant REPLACES the atlas this surface would have sampled.
			# Only ever non-null for a City Kit building (see the caller).
			if roof != null and tex != null:
				tex = roof
			if tex != null:
				mat.albedo_texture = tex
				# Nearest, like the kits' own import: these are palette atlases
				# where one texel is one flat colour, and filtering them bleeds
				# neighbouring swatches into each other along every UV seam.
				mat.texture_filter = BaseMaterial3D.TEXTURE_FILTER_NEAREST
		else:
			mat.albedo_color = tint
		mesh_instance.set_surface_override_material(surface, mat)


## ⚠️ THE TOON MATERIAL AND ITS OUTLINE MUST GET IDENTICAL VALUES.
## They displace the same vertices in two passes; any disagreement shows up as a
## garment sliding around inside a stationary ink border. One setter, called for
## both, so they cannot drift.
func _set_wind(material: ShaderMaterial) -> void:
	material.set_shader_parameter("wind_strength", WIND_STRENGTH)
	material.set_shader_parameter("wind_speed", WIND_SPEED)
	material.set_shader_parameter("wind_anchor_y", WIND_ANCHOR_Y)
	material.set_shader_parameter("wind_drop", WIND_DROP)
